### YamlMime:ManagedReference
items:
- uid: Kobold.Core.Systems.CollisionConfig
  commentId: T:Kobold.Core.Systems.CollisionConfig
  id: CollisionConfig
  parent: Kobold.Core.Systems
  children:
  - Kobold.Core.Systems.CollisionConfig.CollisionMatrix
  - Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
  langs:
  - csharp
  - vb
  name: CollisionConfig
  nameWithType: CollisionConfig
  fullName: Kobold.Core.Systems.CollisionConfig
  type: Class
  source:
    remote:
      path: Kobold/Systems/CollisionSystem.cs
      branch: docs
      repo: https://github.com/toricook/kobold.git
    id: CollisionConfig
    path: Kobold/Systems/CollisionSystem.cs
    startLine: 237
  assemblies:
  - Kobold.Core
  namespace: Kobold.Core.Systems
  summary: Configuration for collision detection and response
  example: []
  syntax:
    content: public class CollisionConfig
    content.vb: Public Class CollisionConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
  commentId: P:Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
  id: EnableCollisionResponse
  parent: Kobold.Core.Systems.CollisionConfig
  langs:
  - csharp
  - vb
  name: EnableCollisionResponse
  nameWithType: CollisionConfig.EnableCollisionResponse
  fullName: Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
  type: Property
  source:
    remote:
      path: Kobold/Systems/CollisionSystem.cs
      branch: docs
      repo: https://github.com/toricook/kobold.git
    id: EnableCollisionResponse
    path: Kobold/Systems/CollisionSystem.cs
    startLine: 239
  assemblies:
  - Kobold.Core
  namespace: Kobold.Core.Systems
  syntax:
    content: public bool EnableCollisionResponse { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property EnableCollisionResponse As Boolean
  overload: Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse*
- uid: Kobold.Core.Systems.CollisionConfig.CollisionMatrix
  commentId: P:Kobold.Core.Systems.CollisionConfig.CollisionMatrix
  id: CollisionMatrix
  parent: Kobold.Core.Systems.CollisionConfig
  langs:
  - csharp
  - vb
  name: CollisionMatrix
  nameWithType: CollisionConfig.CollisionMatrix
  fullName: Kobold.Core.Systems.CollisionConfig.CollisionMatrix
  type: Property
  source:
    remote:
      path: Kobold/Systems/CollisionSystem.cs
      branch: docs
      repo: https://github.com/toricook/kobold.git
    id: CollisionMatrix
    path: Kobold/Systems/CollisionSystem.cs
    startLine: 240
  assemblies:
  - Kobold.Core
  namespace: Kobold.Core.Systems
  syntax:
    content: public CollisionMatrix CollisionMatrix { get; set; }
    parameters: []
    return:
      type: Kobold.Core.Systems.CollisionMatrix
    content.vb: Public Property CollisionMatrix As CollisionMatrix
  overload: Kobold.Core.Systems.CollisionConfig.CollisionMatrix*
references:
- uid: Kobold.Core.Systems
  commentId: N:Kobold.Core.Systems
  href: Kobold.html
  name: Kobold.Core.Systems
  nameWithType: Kobold.Core.Systems
  fullName: Kobold.Core.Systems
  spec.csharp:
  - uid: Kobold
    name: Kobold
    href: Kobold.html
  - name: .
  - uid: Kobold.Core
    name: Core
    href: Kobold.Core.html
  - name: .
  - uid: Kobold.Core.Systems
    name: Systems
    href: Kobold.Core.Systems.html
  spec.vb:
  - uid: Kobold
    name: Kobold
    href: Kobold.html
  - name: .
  - uid: Kobold.Core
    name: Core
    href: Kobold.Core.html
  - name: .
  - uid: Kobold.Core.Systems
    name: Systems
    href: Kobold.Core.Systems.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse*
  commentId: Overload:Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
  href: Kobold.Core.Systems.CollisionConfig.html#Kobold_Core_Systems_CollisionConfig_EnableCollisionResponse
  name: EnableCollisionResponse
  nameWithType: CollisionConfig.EnableCollisionResponse
  fullName: Kobold.Core.Systems.CollisionConfig.EnableCollisionResponse
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Kobold.Core.Systems.CollisionConfig.CollisionMatrix*
  commentId: Overload:Kobold.Core.Systems.CollisionConfig.CollisionMatrix
  href: Kobold.Core.Systems.CollisionConfig.html#Kobold_Core_Systems_CollisionConfig_CollisionMatrix
  name: CollisionMatrix
  nameWithType: CollisionConfig.CollisionMatrix
  fullName: Kobold.Core.Systems.CollisionConfig.CollisionMatrix
- uid: Kobold.Core.Systems.CollisionMatrix
  commentId: T:Kobold.Core.Systems.CollisionMatrix
  parent: Kobold.Core.Systems
  href: Kobold.Core.Systems.CollisionMatrix.html
  name: CollisionMatrix
  nameWithType: CollisionMatrix
  fullName: Kobold.Core.Systems.CollisionMatrix
